### ISSUE TITLE
⚙️ State of the project

### ISSUE THREAD

**Issue by riggraz** [riggraz/astuto#67]
Hey contributors and guests 👋🏻

I've been trying to keep up with Astuto in the last few months but I don't have a lot of free time. And, when I do, I'm not that enthusiastic about working on it.

Anyway it is in my intentions to bring Astuto to a point in which it can be considered a useful and usable software that can be adopted by some users and run in production. **It won't happen soon, but it'll happen.**

A list of the features I will eventually add and I believe are essential to consider Astuto a well-rounded product are:

- [ ] Implement OAuth2 login (#52)
- [ ] Add internationalization
- [ ] Improve installation experience (and also reduce size of Docker image (#58))
- [ ] Add markdown support (#43)
- [ ] Set up a free running demo

Of course if somebody wants to work on these features (or anything else as well) it's more than welcome! In the meanwhile I'll try to keep up with labeling issues and reviewing pull requests.

That's all for now. Bye and see you around the repo 😁👋🏻

**Comment by raphmim** [comment]
@riggraz thanks for this post to let us know about the status!  It's been almost a year, have your thoughts on the future of the project evolved since?

Unfortunately, we are unable to use ClearFlask and Fider as alternatives because of their UX, and LogChimp seems abandonned, so Astuto is still the most promising open-source solution out there.

**Comment by matusfaro** [comment]
@raphmim I would love to hear why ClearFlask doesn't work for you. Please send me an email at matus@clearflask.com

**Comment by riggraz** [comment]
Good news: Astuto is getting back! New feature: admin panel for post status administration (see #105).

I'm closing this issue now because a lot of things have changed in my plans (and also because of spam 😉). Stay tuned!
